---
# tasks file for srv_setup
- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  notify: Install Docker Engine

- name: Create docker directory
  ansible.builtin.file:
    path: /srv/docker
    state: directory
    mode: '755'