---
# tasks file for srv_setup
- name: Password file check
  ansible.builtin.stat:
    path: "{{ 'files/vpn_creds/' + ansible_hostname + '.pwd' }}"
  register: password_file_check
  ignore_errors: true

- name: Generate random and idempotent password
  ansible.builtin.set_fact:
    generated_password: "{{ lookup('password', '/dev/null' + ansible_hostname + '.pwd', length=15, seed=inventory_hostname) }}"
  when: password_file_check.stat.exists is defined and password_file_check.stat.exists == False

- name: Save the generated password to a local file
  ansible.builtin.copy:
    content: "{{ generated_password }}"
    dest: "/tmp/{{ ansible_hostname }}.pwd"
  when: password_file_check.stat.exists is defined and password_file_check.stat.exists == False

- name: Fetch the generated password to a files directory
  ansible.builtin.fetch:
    src: "/tmp/{{ ansible_hostname }}.pwd"
    dest: "{{ role_path + '/files/vpn_creds/' + ansible_hostname + '.pwd' }}"
    flat: yes
  when: password_file_check.stat.exists is defined and password_file_check.stat.exists == False
  notify: Delete local password file

- name: Set IPsec conf
  ansible.builtin.template:
    src: ipsec.conf.j2
    dest: /etc/ipsec.conf
    owner: root
    group: root
    mode: '0644'

- name: Set IPsec secrets
  ansible.builtin.template:
    src: ipsec.secrets.j2
    dest: /etc/ipsec.secrets
    owner: root
    group: root
    mode: '0600'

- name: Set xl2tpd conf
  ansible.builtin.template:
    src: xl2tpd.conf.j2
    dest: /etc/xl2tpd/xl2tpd.conf
    owner: root
    group: root
    mode: '0644'

- name: Set xl2tpd options
  ansible.builtin.template:
    src: options.l2tpd.j2
    dest: /etc/ppp/options.{{ conn_name }}.l2tpd
    owner: root
    group: root
    mode: '0600'
  notify: Start VPN

- name: Set auto add routes
  ansible.builtin.template:
    src: vpn.routes.j2
    dest: /etc/ppp/ip-up.d/{{ conn_name }}.routes
    owner: root
    group: root
    mode: '0755'
  notify: Start VPN