---
# tasks file for srv_setup

- block: # Debian-like servers
  
  - include_tasks: packages.yml

  - include_tasks: repo_keys.yml

  - include_tasks: ssh.yml

  - include_tasks: docker.yml

  - include_tasks: node_exporter.yml

  - include_tasks: ohmyzsh.yml

  - include_tasks: iptables.yml

  - include_tasks: l2tp_ipsec.yml

  when: ansible_os_family == "Debian"