---
# tasks file for srv_setup
- name: "Install node_exporter"
  unarchive:
    src: "{{ node_exporter_pkg }}"
    dest: /srv/
    remote_src: yes

- name: Add User node_exporter
  ansible.builtin.user:
    name: node_exporter
    shell: /bin/false
    system: yes

- name: Set node_exporter daemon
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Start node_exporter

- name: Add new server to prometheus
  ansible.builtin.lineinfile:
    path: "{{ prometheus_config }}"
    line: "    - targets: ['{{ ansible_hostname }}:{{ node_exporter_port }}']"
    create: yes
  delegate_to: localhost
  notify: Restart prometheus