- name: Install ohmyzsh
  shell: |
    if [ ! -d "/{{ ansible_env.USER }}/.oh-my-zsh" ]; then
    printf "y\n" | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)";
    else exit 1
    fi
  ignore_errors: true
  notify:
    - set ohmyzsh theme
    - set zsh as default
    - edit ohmyzsh theme